<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Milex.GMS1.Core</RootNamespace>
    <AssemblyName>Milex_GMS1_CoreMod</AssemblyName>
    <Version>1.3.0</Version>
    <Authors>Milex</Authors>
    <Product>Milex GMS1 CoreMod</Product>
    <Description>Core Modding Framework, Localization and Configuration Menu for Gold Mining Simulator</Description>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\*.json" />
  </ItemGroup>
</Project>
